name = "LibNTL"
uuid = "f5c7a3e2-8d9b-4c1f-a5e6-7b8c9d0e1f2a"
version = "0.1.0"
authors = ["LibNTL Contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
